config/routes.rb
Rails.application.routes.draw do
  resources :newsletter_signups, only: :create
  root "home#index"
  get "pitr", to: "home#pitr"
  delete "pitr", to: "home#important_delete", as: :delete_info
  post "pitr", to: "home#create_info", as: :create_info

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/important_info.rb
class ImportantInfo < ApplicationRecord
end

app/models/newsletter_signup.rb
class NewsletterSignup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @newsletter_signup = NewsletterSignup.new
  end

  def pitr
    @important_infos = ImportantInfo.all.limit(1000).order(created_at: :desc)
  end

  def important_delete
    ImportantInfo.delete_all
    redirect_to pitr_path
  end

  def create_info
    10.times { ImportantInfo.create! }
    redirect_to pitr_path
  end
end

app/controllers/newsletter_signups_controller.rb
class NewsletterSignupsController < ApplicationController
  def create
    @newsletter_signup = NewsletterSignup.new(newsletter_params)
    if @newsletter_signup.save
      NotifyUserJob.perform_later(@newsletter_signup.id)
      flash[:notice] = "Subscribed!"
      redirect_to root_path
    else
      flash[:alert] = "Failed!"
      render "home/index"
    end
  end

  private

    def newsletter_params
      params.require(:newsletter_signup).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsletter_signup_helper.rb
module NewsletterSignupHelper
end

app/views/home/index.html.erb
<div class="stack stack-lg mx-auto">
  <div class="stack">
    <h1 class="font-bold text-xl">Simple Host</h1>
    <p class="tny-txt">How to host simply, cheaply</p>
  </div>
  <div class="crd mx-auto shadow-hard">
    <p class="heading">Simple Rails hosting tips, occasionally</p>
    <%= form_with model: @newsletter_signup, class: "frm" do |form| %>
      <%= form.label :email %>
      <%= form.email_field :email %>
      <%= form.submit "Register", class: "" %>
    <% end %>

  </div>

  <div class="spaced-cluster pll info mx-auto w-[20ch] text-lg">
    <p>Sign ups</p>
    <p><%= NewsletterSignup.count %></p>
  </div>

</div>

app/views/home/pitr.html.erb
<% timestr = "%Y-%m-%d %H:%M:%S" %>

<div class="stack-lg mx-auto max-w-[55ch] w-[55ch] mb-12">
  <p><%= "Now: #{Time.current.strftime(timestr)}" %></p>
  <%= form_with url: delete_info_path, method: :delete do |f| %>
    <button
      class="
        p-10
        text-lg
        bg-red-100
        text-red-800
        rounded
        border
        border-red-200
        w-full
      "
    >
      DO NOT PRESS!
    </button>
  <% end %>

  <%= form_with url: create_info_path, method: :post do |f| %>
    <button
      class="
        p-10
        text-lg
        bg-green-100
        text-green-900
        rounded
        border
        border-green-200
        w-full
      "
    >PRESS!</button>
  <% end %>

  <div class="stack">
    <% @important_infos&.each do |ii| %>
      <div class="spaced-cluster border p-4 rounded text-gray-700">
        <p class="min-w-[10ch]"><%= ii.id %></p>
        <p class="font-bold">IMPORTANT USER INFO</p>
        <p><%= ii.created_at.strftime(timestr) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleHost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/newsletter_signup/create.html.erb
<div>
  <h1 class="font-bold text-4xl">NewsletterSignup#create</h1>
  <p>Find me in app/views/newsletter_signup/create.html.erb</p>
</div>